### ISSUE TITLE
Error when one of the NS servers does not have AAAA record

### ISSUE THREAD

**Issue by lamiska** [nuxi/acme-tiny#6]
Hi, I am trying to generate certificate for one of my domains. This domain has 3 NS servers:

ns1.superhosting.cz - has both A and AAAA records
ns2.superhosting.cz - has both A and AAAA records
ns3.superhosting.cz  - has only A record

which results in this error:

```
Traceback (most recent call last):
  File "/usr/sbin/acme_tiny.py", line 272, in <module>
    main(sys.argv[1:])
  File "/usr/sbin/acme_tiny.py", line 268, in main
    dns_update_algo=dns_update_algo)
  File "/usr/sbin/acme_tiny.py", line 178, in get_crt
    addr = addr.union(map(str, dns.resolver.query(str(x), 'AAAA')))
  File "/usr/lib/python2.7/dist-packages/dns/resolver.py", line 1132, in query
    raise_on_no_answer, source_port)
  File "/usr/lib/python2.7/dist-packages/dns/resolver.py", line 1053, in query
    raise_on_no_answer)
  File "/usr/lib/python2.7/dist-packages/dns/resolver.py", line 234, in __init__
    raise NoAnswer(response=response)
dns.resolver.NoAnswer: The DNS response does not contain an answer to the question: ns3.superhosting.cz. IN AAAA
```

By using ```--skip``` argument you can skip check of DNS records without any errors.

**Comment by nuxi** [comment]
Ooops. I bet it also does something dumb if a AAAA record is there but the box running the script has no IPv6 connectivity.

**Comment by nuxi** [comment]
Sorry about that, I didn't realize DNS python threw an exception in when there were no results instead of just returning en empty set.

Fixed: https://github.com/nuxi/acme-tiny/commit/ee754f6faff27031a83b6b5a88b795ee4b5ca8fc
